### ISSUE TITLE
Error message when loading XDF in TP

### ISSUE THREAD

**Issue by speedyweber** [saildot4k/MSS54-XDFs#10]
Using Tunerpro, trying to load hw2101_v4, both basic and complete, result in an error message from TP. Unsure how to solve the issue.
![Capture](https://user-images.githubusercontent.com/54147741/63107055-78ae9e80-bf41-11e9-906f-fda3204e241c.JPG)

Every xdf from 1401 up results in this error message. 0301, 0401, and 1301 open without issue.

I am not a coder but can follow basic instructions, and I'm more than willing to donate something for your time.

**Comment by saildot4k** [comment]
Try shortening your file path. Tunerpro seems to have a problem with that at times. Just opened all to check, no problems here.  Also make sure you have unzipped the download instead of trying to open from within. Report back please.

**Comment by kmalinich** [comment]
When I originally cloned the repo with Git (not downloading a ZIP) and tried to open directly in TunerPro, I had the same issue, IIRC. (95% of the dev work I do is UTF-8 with Unix line endings). I fixed it by running unix2dos on the files. It may be occurring due to a local Git config setting. 

@speedyweber did you clone the repo or did you download the ZIP file and unzip it?
